### ISSUE TITLE
HELP NEEDED!!

### ISSUE THREAD

**Issue by e-coders** [Educational-Websites/LiveCodeEditor2#1]
HELP NEEDED!!
Tabs aren't working.
Help pls!!
Uncaught TypeError: showPreview() is not definied.

**Comment by Genius398** [comment]
what

**Comment by e-coders** [comment]
oh yeah!! now Fixed!! As I updated the files, after a minutes it doesn't came, now Fixed!! nothing

**Comment by Genius398** [comment]
:)
